import Head from "next/head";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter clone app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-7xl mx-auto items-start">
        {/* sidebar */}
        <Sidebar />
        {/* feed */}
        <div className="space-y-10">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            recusandae quo architecto est inventore, voluptates vero tenetur
            distinctio perspiciatis, a totam sunt esse consequatur quam iusto,
            sit ut minus quasi.
          </p>
        </div>
        {/* widgets */}
        widgets area
      </main>
    </>
  );
}
